* src/plugins/WebPage.py: Fixed ID link so that link references are not converted to &lt; and &gt; * src/plugins/WriteGedcom.py: Fixed undefined reference to ref_text
svn: r2205